### ISSUE TITLE
contribute to KerasCV?

### ISSUE THREAD

**Issue by LukeWood** [miguelCalado/prompt-to-prompt-tensorflow#3]
Hey Miguel!

Luke here from KerasCV!  Pleasure to meet you. Would you be interested in contributing this as an API to KerasCV?  https://github.com/keras-team/keras-cv ?

If so, I will open an issue, assign to you, and you can tag me on the PRs.

**Comment by miguelCalado** [comment]
Hey @LukeWood!

Thanks so much for reaching out. Yeah, sure go ahead and open an issue. It will be my pleasure to contribute!

Just need to re-arrange the code a bit and it should be good to go for a review.

Cheers.
